# Code generated by scripts/gen-contract.js from contract/contract.json; DO NOT EDIT.
# Single source of truth: ai-native-cli-spec/template/common/contract/contract.json.

SCHEMA_VERSION = "1.0"

# Canonical error-code table: name -> {exit, retryable, core}.
CODES = {
    "E_INTEGRITY": {"exit": 1, "retryable": False, "core": True},
    "E_IO": {"exit": 1, "retryable": False, "core": True},
    "E_UNKNOWN": {"exit": 1, "retryable": False, "core": True},
    "E_USAGE": {"exit": 2, "retryable": False, "core": True},
    "E_VALIDATION": {"exit": 2, "retryable": False, "core": True},
    "E_NOT_FOUND": {"exit": 3, "retryable": False, "core": True},
    "E_AUTH": {"exit": 4, "retryable": False, "core": True},
    "E_CONFIG": {"exit": 4, "retryable": False, "core": True},
    "E_FORBIDDEN": {"exit": 4, "retryable": False, "core": True},
    "E_CONFIRMATION_REQUIRED": {"exit": 5, "retryable": False, "core": True},
    "E_CONFLICT": {"exit": 6, "retryable": False, "core": True},
    "E_NETWORK": {"exit": 7, "retryable": True, "core": True},
    "E_RATE_LIMITED": {"exit": 7, "retryable": True, "core": True},
    "E_SERVER": {"exit": 7, "retryable": True, "core": True},
    "E_TIMEOUT": {"exit": 8, "retryable": True, "core": True},
    "E_INTERRUPTED": {"exit": 130, "retryable": True, "core": True},
    "E_CHANGESET_INVALID": {"exit": 2, "retryable": False, "core": False},
    "E_PROJECT_INVALID": {"exit": 2, "retryable": False, "core": False},
    "E_BACKEND_UNAVAILABLE": {"exit": 4, "retryable": False, "core": False},
}


def exit_for(code):
    """Canonical process exit code for an E_* code (1 if unknown)."""
    spec = CODES.get(code)
    return spec["exit"] if spec else 1


def retryable(code):
    """Whether an agent may back off and retry an E_* code."""
    spec = CODES.get(code)
    return bool(spec["retryable"]) if spec else False


SUCCESS_ENVELOPE_KEYS = ["ok", "schema_version", "data", "meta"]
ERROR_ENVELOPE_KEYS = ["ok", "schema_version", "error", "meta"]
ERROR_OBJECT_KEYS = ["code", "message", "details", "retryable"]
META_REQUIRED_KEYS = ["duration_ms"]
META_OPTIONAL_KEYS = ["notices"]
